### PR TITLE
Express server

### PR DESCRIPTION
**Pull request by rfpoulos**
@NickWilsonDev @codingandcaring not able to truly test until there is a functioning db, but this creates a server architecture of public and private routes.  The private routes will require a token to be in the header to complete and fetch requests.  The public route currently has only one post request route which returns a token to a valid user.  I expect that token will ultimately be held in state in the front end.  private.js currently has no routes, but my next step will be to split that into routes for administers and regular users.

### CODE REVIEW

**Comment by codingandcaring** [comment]
Has there been testing through Postman or similar to ensure that the post requests work?

**Comment by rfpoulos** [comment]
@codingandcaring  I can't really test until I have the DB up and running.  I would like to merge this so I can make a new branch to work on other server stuff.  You have my scouts honor on testing as soon as I have a database.

**Comment by rfpoulos** [comment]
@codingandcaring @NickWilsonDev  Please review.  Now allows a post request to create a user.  When username and password sent to sign-in, returns a token.

**Comment by NickWilsonDev** [comment]
looks good :shipit:

**Pull request merged**
